process.env.NEXT_PUBLIC_FIREBASE_API_KEY = 'AIzaSyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = 'nexus-test.firebaseapp.com';
process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID = 'nexus-test';
process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = 'nexus-test.appspot.com';
process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = '000000000000';
process.env.NEXT_PUBLIC_FIREBASE_APP_ID = '1:000000000000:web:000000000000';
process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = 'G-0000000000';
