export const SUBJECTS_BY_GRADE: Record<string, string[]> = {
  '1ano-em': [
    'Língua Portuguesa',
    'Leitura e Produção de Textos',
    'Inglês',
    'Literatura',
    'Arte',
    'Filosofia',
    'Sociologia',
    'Geografia Humana',
    'Geografia Física',
    'História do Brasil',
    'História Geral',
    'História da América',
    'Química 1',
    'Química 2',
    'Biologia 1',
    'Biologia 2',
    'Física 1',
    'Física 2',
    'Matemática Básica',
    'Álgebra',
    'Geometria',
  ],
  '2ano-em': [
    'Língua Portuguesa',
    'Leitura e Produção de Texto',
    'Arte',
    'Inglês',
    'Literatura',
    'Filosofia',
    'Sociologia',
    'História do Brasil',
    'História Geral',
    'História Contemporânea',
    'Geografia Física',
    'Geografia Humana',
    'Geografia Política',
    'Química Orgânica',
    'Físico-Química',
    'Física 1',
    'Física 2',
    'Física 3',
    'Biologia 1',
    'Biologia 2',
    'Biologia 3',
    'Matemática Básica',
    'Álgebra',
    'Geometria',
  ],
};

export const GRADE_LABELS: Record<string, string> = {
  '1ano-em': '1ª Série',
  '2ano-em': '2ª Série',
};
